### ISSUE TITLE
Could not resolve dependencies for project com.cevher.keycloak:custom-event-listener:jar:0.0.1

### ISSUE THREAD

**Issue by dienleptn** [cevheri/keycloak-custom-event-listener#1]
Hi guys, I have cloned the repository and run 'mvn clean package' then I have a issue like below

Failed to execute goal on project custom-event-listener: Could not resolve dependencies for project com.cevher.keycloak:custom-event-listener:jar:0.0.1: The following artifacts could not be resolved: org.keycloak:keycloak-core:jar:0.0.1 (absent), org.keycloak:keycloak-server-spi:jar:0.0.1 (absent), org.keycloak:keycloak-server-spi-private:jar:0.0.1 (absent), org.keycloak:keycloak-services:jar:0.0.1 (absent), org.keycloak:keycloak-saml-core-public:jar:0.0.1 (absent): org.keycloak:keycloak-core:jar:0.0.1 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced

Can you please give an idea to fix this error?
Thanks

**Comment by cevheri** [comment]
yes I saw this error
thanks for sharing
